#! /bin/sh -e

#
# mksocktlist -- generate C source involving lists of known socket types
# Copyright (C) 2000  Andrew Main
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

INPUT_FILE=$1
OUTPUT_FILE=$2

get_template='
	/^# *include *<'$OUTPUT_FILE'> *\/\*/{
		s/^[^>]*> \/\*//
		s/\*\/.*$//
		p
	}
'
tolower='y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/'

template=`sed -n "$get_template" < $INPUT_FILE`
template="#ifdef SOCK_@TYPE@
$template
#endif /* SOCK_@TYPE@ */"

for bigtype in DGRAM PACKET RAW RDM SEQPACKET STREAM WEB; do
	littletype=`echo $bigtype | sed "$tolower"`
	echo "$template" | sed 's/@TYPE@/'$bigtype'/g;s/@type@/'$littletype'/g'
done > $OUTPUT_FILE
exit 0
