#! /bin/sh -e

#
# Lib/mkprotos -- generate protocol parsing code
# Copyright (C) 2000  Andrew Main
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

SPEC=$1

clean='
	s/[	 ][	 ]*//g
	/^$/d
	/^#/d
'
idrange='a-zA-Z0-9_'
idchar="[$idrange]"

mkprototypes=$clean'
	s/^\('$idchar$idchar'*\):/struct ilayer *unsn_private_mkilayer_\1(/
	s/\['$idchar'*]/struct sstring const *, /g
	s/, $/);/
'
mkenum=$clean'
	s/^\('$idchar$idchar'*\):.*$/	ILAYER_\1,/
'

(
	sed "$mkprototypes" < $SPEC
	echo
	echo 'enum {'
	sed "$mkenum" < $SPEC
	echo '	ILAYER_'
	echo '};'
) > ilayers.h

mktable=$clean'
	s/^\('$idchar$idchar'*\):.*$/	"\1",/
'

(
	echo 'static char const * const protos[] = {'
	sed "$mktable" < $SPEC
	echo '};'
) > ilayers.t.ic

mkinterp=$clean'
	h
	s/^\('$idchar$idchar'*\):.*$/case ILAYER_\1: {/
	p
	s/^.*$/	struct unsn_a_option const *op = l->options;/
	p
	g
	s/^'$idchar$idchar'*://
	s/\[\('$idchar'*\)]/	struct sstring const *opt_\1 = (op->name \&\& !cmpsstrstr(op->name, "\1")) ? op++->value : NULL;@/g
	s/@$//
	p
	s/^.*$/	if(op->name) {@		errno = UNSN_EUNSNBADOPTION;@		return NULL;@	}/
	p
	g
	s/^\('$idchar$idchar'*\):/	return unsn_private_mkilayer_\1(/
	s/\[\('$idchar'*\)]/opt_\1, /g
	s/, $//
	s/$/);/
	p
	s/^.*$/}/
	p
'
sed -n "$mkinterp" < $SPEC | tr @ '\012' > ilayers.i.ic
