#! /bin/sh -e

#
# mkmanpages -- generate man pages under multiple names
# Copyright (C) 2000  Andrew Main
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

. $1
OUTPUT_DIR=$2
shift 2

sed_prog='
	/^\.\\" NAMES: /{
		s/^\.\\" NAMES: //
		p
	}
'

for INPUT in $@; do
	NAMES=`sed -n "$sed_prog" < $INPUT`
	for NAME in $NAMES; do
		sed '
			2s/^\.\\" [^ ]*/.\\" '${NAME}'/
			/^\.\\" NAMES: /d
			s/@VERSION@/'${VERSION}'/g
			s/@DATE@/'${DATE}'/g
		' < $INPUT > ${OUTPUT_DIR}/$NAME
		echo $NAME
	done
done

exit 0
